name: stargeo-prod
services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${PGUSER:-postgres}" ]
      interval: 1s
      timeout: 10s
      retries: 50

  redis:
    image: redis:3
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: bedasoftware/stargeo:latest
    command: ./run_gunicorn.sh
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8001:8000"
    env_file: .env

  celery:
    image: bedasoftware/stargeo:latest
    command: celery -A stargeo worker -l info
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      C_FORCE_ROOT: "True"
