services:
  app:
    volumes:
    - .:/app/user
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db/star"
      REDIS_HOST: redis
      BROKER_URL: redis://redis/1

  celery:
    volumes:
    - .:/app/user
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db/star"
      REDIS_HOST: redis
      BROKER_URL: redis://redis/1
      C_FORCE_ROOT: "True"

  frontend:
    build:
      context: frontend
    command: yarn dev
    volumes:
    - ./frontend:/app/user
    ports:
    - 8082:8082
