db:
  image: postgres:9.4

redis:
  image: redis:3

server:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  links:
  - db
  - redis
  ports:
  - "8000:8000"
  env_file: .env

celery:
  build: .
  command: honcho start celery
  links:
  - db
  - redis
  env_file: .env
