name: Build
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Build and release image to Docker Hub
    runs-on: ubuntu-latest
    env:
      BUILD_IMAGE: bedasoftware/stargeo:latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: >-
          docker buildx build --platform linux/arm64,linux/amd64
          -f Dockerfile.prod
          --push -t ${{ env.BUILD_IMAGE }} .