name: Upload docker compose config to server and restart containers
on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [master]
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Upload and Restart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.REMOTE_HOST}}
          username: ${{secrets.REMOTE_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          source: "compose.prod.yaml"
          target: "app"
      - name: Restart
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.REMOTE_HOST}}
          username: ${{secrets.REMOTE_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script_stop: true
          script: |
            cd app
            make restart
            echo Containers were restarted